# Generated by Django 5.1.5 on 2025-01-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
