# Generated by Django 5.0.1 on 2025-01-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lead Price'),
        ),
    ]
