# Generated by Django 5.0.1 on 2025-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='lead',
            name='validity',
            field=models.CharField(blank=True, choices=[('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], max_length=20, null=True, verbose_name='Lead Validity'),
        ),
    ]
