# Generated by Django 5.0.1 on 2025-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_city_lead_country_lead_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='validity',
            field=models.CharField(blank=True, choices=[('1_hr', '1 Hr'), ('3_hr', '3 Hr'), ('6_hr', '6 Hr'), ('12_hr', '12 Hr'), ('1_day', '1 Day'), ('2_day', '2 Day'), ('1_week', '1 Week')], max_length=20, null=True, verbose_name='Lead Validity'),
        ),
    ]
