# Generated by Django 5.0.1 on 2025-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='map_location',
            field=models.URLField(blank=True, null=True, verbose_name='Map Location'),
        ),
    ]
