# Generated by Django 5.1.5 on 2025-01-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometric',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometric',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biometric',
            name='verification_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence score of biometric verification'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interaction_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(default=1, help_text='Notification priority (1-5)'),
        ),
    ]
